server:
  port: 8080

spring:
  application:
    name: compiler-backend
  profiles:
    active: development

app:
  base-url: http://localhost:3000
  execution:
    mode: mock # Can be 'docker' or 'mock'
    timeout: 10
    memory-limit: 128m
    cpu-limit: 0.5

logging:
  level:
    com.example.compiler: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: development

app:
  execution:
    mode: mock

---
spring:
  config:
    activate:
      on-profile: production

app:
  execution:
    mode: docker
